### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by ThomasGuerneve** [gabyx/ApproxMVBB#1]
Just tried to build the latest version 1.0.9 and it looks like an error has been introduced in the CMakeList, this happens when trying to build the library, here is the log :

-- Module path is now set to: /home/thomas.guerneve/Code/ApproxMVBB/cmake/
-- Project name is: ApproxMVBB-Release
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Compiler ID is: GNU
-- Setting Values for GNU
-- Set make program to /home/thomas.guerneve/Code/ApproxMVBB/build/parallelmake.sh
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found PugiXML: /usr/lib/x86_64-linux-gnu/libpugixml.so  
-- PugiXML include = /usr/include
-- PugiXML library = /usr/lib/x86_64-linux-gnu/libpugixml.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Meta: find meta
-- Meta: Setup External Projext
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- /home/thomas.guerneve/Code/ApproxMVBB/build/src/meta/include
-- Found Meta: /home/thomas.guerneve/Code/ApproxMVBB/build/src/meta/include  
-- Added  to CMAKE_CXX and CMAKE_C_FLAGS: -std=c++11 -fmax-errors=50  and -fmessage-length=0 -fmax-errors=50 
-- Adding  ApproxMVBB - Diameter ======================
-- ====================================================
-- Adding  ApproxMVBB - GeometryPredicates ============
-- Performing Test HAVE__FPU_SETCW
-- Performing Test HAVE__FPU_SETCW - Success
-- Performing Test HAVE_FPSETPREC
-- Performing Test HAVE_FPSETPREC - Failed
-- Performing Test HAVE__CONTROLFP
-- Performing Test HAVE__CONTROLFP - Failed
-- Performing Test HAVE__CONTROLFP_S
-- Performing Test HAVE__CONTROLFP_S - Failed
-- Performing Test HAVE_FPU_INLINE_ASM_X86
-- Performing Test HAVE_FPU_INLINE_ASM_X86 - Success
-- Floating point control:
                HAVE__FPU_SETCW 1 
                HAVE_FPSETPREC  
                HAVE__CONTROLFP  
                HAVE__CONTROLFP_S  
                HAVE_FPU_INLINE_ASM_X86 1
-- Generate : /home/thomas.guerneve/Code/ApproxMVBB/build/include/ApproxMVBB/GeometryPredicates/PredicatesInit.hpp
-- Make project depend on target ApproxMVBB-Release_PredInitGen!
-- ====================================================
-- ApproxMVBB Version: 1.0.9 extracted from git tags!
CMake Error at lib/CMakeLists.txt:35 (if):
  if given arguments:

```
"NOT" "ApproxMVBB-Release_PredInitGen" "meta" "STREQUAL" ""
```

  Unknown arguments specified

-- Configuring incomplete, errors occurred!
See also "/home/thomas.guerneve/Code/ApproxMVBB/build/CMakeFiles/CMakeOutput.log".
See also "/home/thomas.guerneve/Code/ApproxMVBB/build/CMakeFiles/CMakeError.log".

**Comment by gabyx** [comment]
Damn, forgot to quote the if statement :-)

please try again with the latest master (d46a8f0499b454a1189531f4077a3c7b741a7f89)

Thanks for helping to make things bomb proof :-)

BR

**Comment by ThomasGuerneve** [comment]
Ok thanks, same issues to be fixed in example/approxMVBB/CMakeLists.txt & ApproxMVBB/example/kdTreeFiltering/CMakeLists.txt
It seems to build fine now, good job !
Thanks
Thomas G

Date: Tue, 7 Jul 2015 14:02:49 -0700
