### ISSUE TITLE
How to modify elements in Matrix3Dyn?

### ISSUE THREAD

**Issue by soulslicer** [gabyx/ApproxMVBB#14]
The given example shows you how to initialize a set of points dynamcally:

> ApproxMVBB::Matrix3Dyn points(3,10000);

However, since I cant seem to figure out how to modify certain points at certain indices. Are there accessors as such

>  points[pointNum][0, 1 or 2 for xyz];

**Comment by Maghoumi** [comment]
Hi,
Eigen library has overloaded operator()  on all of the types. You can use
eg. "points(5,10) = 5;" to assign to the element at row 5 column 10.
