### ISSUE TITLE
What are lower point and upper point in the OOBB object?

### ISSUE THREAD

**Issue by caihaoye16** [gabyx/ApproxMVBB#17]
Are they the two vertices on the diagonal?

**Comment by gabyx** [comment]
Correct, `oobb.m_minPoint`and `oobb.m_maxPoint` are the minimal and maximal Point in the Coordinate System of the object oriented bounding box `oobb` which is given by the transformation matrix:
```
oobb.m_q_KI.matrix() 
```
which is the rotation matrix R_KI  which turns the world frame I into the OOBB frame K.
This is the transformation matrix A_IK which turns a coordinate tuple `K_x` in  coordinate system K into a coordinate tuple `I_x` in coordinate system I , by `I_x = A_IK * K_x` 

See the example/approxMVBB/src/main.cpp
