### ISSUE TITLE
build_and_test error

### ISSUE THREAD

**Issue by jingfeng-linksprite** [gabyx/ApproxMVBB#19]
5: [  FAILED  ] MVBBTest.PointClouds (1438 ms)
5: [----------] 12 tests from MVBBTest (9691 ms total)
5: 
5: [----------] Global test environment tear-down
5: [==========] 12 tests from 1 test case ran. (9691 ms total)
5: [  PASSED  ] 11 tests.
5: [  FAILED  ] 1 test, listed below:
5: [  FAILED  ] MVBBTest.PointClouds
5: 
5:  1 FAILED TEST
5/5 Test #5: ApproxMVBBTests-MVBB .............***Failed    9.69 sec

60% tests passed, 2 tests failed out of 5

Total Test time (real) =  11.27 sec

The following tests FAILED:
	  1 - ApproxMVBBTests-ConvexHull (Failed)
	  5 - ApproxMVBBTests-MVBB (Failed)
Errors while running CTest
make[3]: *** [CMakeFiles/build_and_test] Error 8
make[2]: *** [CMakeFiles/build_and_test.dir/all] Error 2
make[1]: *** [CMakeFiles/build_and_test.dir/rule] Error 2
make: *** [build_and_test] Error 2

**Comment by gabyx** [comment]
Could you append, the whole test output...
Thanks!

**Comment by gabyx** [comment]
I ve just seen that I was working on replacing the old random tests, since the random generator had some bug (hm... :-) ...: I will soon comit in master to make the test working
