### ISSUE TITLE
Make issue - 

### ISSUE THREAD

**Issue by soulslicer** [gabyx/ApproxMVBB#2]
I seem to get the following issue:

http://pastebin.com/inuaFYFC

The error appears to be on the example/kdTreeFiltering:

/home/raaj/ApproxMVBB/include/ApproxMVBB/KdTree.hpp: In member function ‘void ApproxMVBB::KdTree::TreeStatistics::appendToXML(ApproxMVBB::KdTree::TreeStatistics::XMLNodeType&)’:
/home/raaj/ApproxMVBB/include/ApproxMVBB/KdTree.hpp:1721:109: error: call of overloaded ‘set_value(long long unsigned int)’ is ambiguous
             stat.append_attribute("m_minLeafDataSize").set_value( (long long unsigned int)m_minLeafDataSize );

**Comment by gabyx** [comment]
Hi, this might be , due to Compilation of Pugixml, without the flag:
#define PUGIXML_HAS_LONG_LONG
in 

pugiconfig.hpp

Can you try to reinstall, pugixml and then report back here

Thanks for this, I make a note in the documentation!

**Comment by gabyx** [comment]
I close this issue!, Reopen it when the problem persists

**Comment by soulslicer** [comment]
Ok sure. Btw you should consider adding support or conversion support for PCL.

**Comment by gabyx** [comment]
Jeah, that is planned in the future. 
I think the PCL PointCloud can be used directly , I am bit busy right now but, I should add a "how to use it"

IN the meantime, you can try to understand the example, and wrap your own point cloud of PCL into it... . It should somehow work, since you only need to adapt the wrappers  , see ->

`using PointDataTraits = KdTree::DefaultPointDataTraits<3,Vector3, MyPoint, MyPointGetter>;`

in the kdTreeExample

**Comment by jingfeng-linksprite** [comment]
How to compile pugixml? I used sudo apt-get install libpugixml-dev and got same error.

**Comment by gabyx** [comment]
I think you should install pugixml manually with cmake : Set the flag : PUGIXML_HAS_LONG_LONG

**Comment by jingfeng-linksprite** [comment]
I used "$ cmake --PUGIXML_HAS_LONG_LONG ./."  still get same error. However, the error goes away if I just delete all pugixml stuff.  I can build the code although cmake complains that if cannot find pugixml.

**Comment by soulslicer** [comment]
Same here.

It's sad that people can't use your code just because of this Pugixml dependency and all that is doing is xml parsing.

**Comment by gabyx** [comment]
Pugixml is optional, You can disable it in the cmake cache by setting ApproxMVBB_SUPPORT_XML = OFF. if that does not work its a bug I need to fix. Maybe the new version of pugixml has some problems. I will have a look at it, thanks for reporting!
