### ISSUE TITLE
why windows has  not been supported? 

### ISSUE THREAD

**Issue by DamonsJ** [gabyx/ApproxMVBB#25]
why windows has  not been supported?  Will windows be supported? when?

**Comment by gabyx** [comment]
It is supported, I think people are compiling it on windows. Have you tried? It should basically work, but I dont give my word for it, thats why I dont include it in the supported OS. KDTree is definitely not supported, as Eric Nieblers meta library is not supported with the shitty MSVC compiler. XMLSupport mighty work I think.

**Comment by gabyx** [comment]
Current master branch support VS 15, and probably also VS 17
