### ISSUE TITLE
Still asking for git.exe with cmake on windows

### ISSUE THREAD

**Issue by adam-hartshorne** [gabyx/ApproxMVBB#29]
After recloning and attempting to use cmake, it is still asking for git.exe location and won't generate a project without it.

And even when I add a link to git.exe, I still get the following error,

ApproxMVBB Version:  extracted from git tags!
CMake Error at cmake/DefineVersion.cmake:18 (message):
  Error in getting version of ApproxMVBB CMake Error at
  cmake/GetGitRevisionDescriptionExtern.cmake:6 (message):

    ApproxMVBB library version could not be determined!, GIT-NOTFOUND

**Comment by gabyx** [comment]
please paste the command line you use to configure with cmake on windows.
on the command line you have `git` in the path?. Check by executing git in the shell where you launch the `cmake ...` configure statement

**Comment by gabyx** [comment]
Reopen if still a problem
