### ISSUE TITLE
Make install failed 

### ISSUE THREAD

**Issue by Vi-Sri** [gabyx/ApproxMVBB#30]
I am trying to build ApproxMVBB, While doing make install, i am getting the following error. I have installed the dependencies. Please help. 

> **[ 66%] Building CXX object tests/CMakeFiles/ApproxMVBBTest-Diameter.dir/src/TestFunctions.cpp.o
> cd /home/ml/github_projects/ApproxMVBB/ApproxMVBB_Build/tests && /usr/bin/c++   -I/home/ml/github_projects/ApproxMVBB/tests/include -I/home/ml/github_projects/ApproxMVBB/ApproxMVBB_Build/tests/include -I/home/ml/github_projects/ApproxMVBB/external/GeometryPredicates/include -I/home/ml/github_projects/ApproxMVBB/external/Diameter/include -I/home/ml/github_projects/ApproxMVBB/include -I/home/ml/github_projects/ApproxMVBB/ApproxMVBB_Build/include -isystem /usr/local/include/eigen3 -isystem /home/ml/github_projects/ApproxMVBB/ApproxMVBB_Build/thirdparty/googletest-src/googletest/include -isystem /home/ml/github_projects/ApproxMVBB/ApproxMVBB_Build/thirdparty/googletest-src/googletest -isystem /home/ml/github_projects/ApproxMVBB/ApproxMVBB_Build/thirdparty/googletest-src/googlemock/include -isystem /home/ml/github_projects/ApproxMVBB/ApproxMVBB_Build/thirdparty/googletest-src/googlemock  -Wall -Wpedantic -Wno-comment -DApproxMVBB_BUILD_TESTS -std=c++14 -o CMakeFiles/ApproxMVBBTest-Diameter.dir/src/TestFunctions.cpp.o -c /home/ml/github_projects/ApproxMVBB/tests/src/TestFunctions.cpp
> In file included from /home/ml/github_projects/ApproxMVBB/tests/src/TestFunctions.cpp:10:0:
> /home/ml/github_projects/ApproxMVBB/tests/include/TestFunctions.hpp:42:39: error: redefinition of ‘template<class Type> using StdVecAligned = ApproxMVBB::MyContainers::StdVecAligned<Type>’
>          ApproxMVBB_DEFINE_MATRIX_TYPES;
>                                        ^
> In file included from /home/ml/github_projects/ApproxMVBB/tests/include/TestFunctions.hpp:24:0,
>                  from /home/ml/github_projects/ApproxMVBB/tests/src/TestFunctions.cpp:10:
> /home/ml/github_projects/ApproxMVBB/tests/include/CommonFunctions.hpp:24:39: note: ‘template<class Type> using StdVecAligned = ApproxMVBB::MyContainers::StdVecAligned<Type>’ previously declared here
>          ApproxMVBB_DEFINE_MATRIX_TYPES;
>                                        ^
> tests/CMakeFiles/ApproxMVBBTest-Diameter.dir/build.make:78: recipe for target 'tests/CMakeFiles/ApproxMVBBTest-Diameter.dir/src/TestFunctions.cpp.o' failed**
>

**Comment by gabyx** [comment]
which compiler. I wil have a look tomorrow. 
Seems to be a macro error. So far you can skip building the tests. See cmake and Readme

$ c++ —version

**Comment by gabyx** [comment]
Reopen if still a problem
