### ISSUE TITLE
Unable to Compile the sample program.

### ISSUE THREAD

**Issue by mogayo** [gabyx/ApproxMVBB#32]
When i compile sample program (given below),  the compilation was successful,
but i got hit with run time error that is :

"
**==30199==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.**
"

How can i resolve this issue ?

---SAMPLE CODE-- as in example

#include <iostream>
 #include "ApproxMVBB/ComputeApproxMVBB.hpp"

    int  main(int argc, char** argv)
    {
          ApproxMVBB::Matrix3Dyn points(3,10000);
          points.setRandom();
          ApproxMVBB::OOBB oobb = ApproxMVBB::approximateMVBB(points,0.001,500,5,0,5);
          oobb.expandToMinExtentRelative(0.1);
          return 0;
    }

**Comment by gabyx** [comment]
Huch, its the AddressSanitizer which is switched on in Debug. You can turn it off in CMAKE by
removing the flags: 

https://github.com/gabyx/ApproxMVBB/blob/c9e4e8ac09b52ad3a60d0dc827ec888ae62e972e/cmake/SetTargetCompileOptions.cmake#L8

and 

https://github.com/gabyx/ApproxMVBB/blob/c9e4e8ac09b52ad3a60d0dc827ec888ae62e972e/cmake/SetTargetCompileOptions.cmake#L20
https://github.com/gabyx/ApproxMVBB/blob/c9e4e8ac09b52ad3a60d0dc827ec888ae62e972e/cmake/SetTargetCompileOptions.cmake#L21

**Comment by gabyx** [comment]
I would need to further debug this problem...

**Comment by gabyx** [comment]
Reopen if it is still a problem
