### ISSUE TITLE
Low performance even with small number of sampling points

### ISSUE THREAD

**Issue by jediofgever** [gabyx/ApproxMVBB#37]
Hi, 
Thank you for excellent library. I am using this lib to construct a min volume box around object, the accuracy is pretty good even with small number of sampling points but the performance isn't that desirable. I follow standard compilation steps listed in readme, in default the openMP is enabled but I am not sure if the parallelization is indeed utilized. Could you address some of the places to check about the speed improvement. Thank you for your time

**Comment by gabyx** [comment]
Search for `ApproxMVBB_OPENMP_SUPPORT`
Maybe you could directly do some benchmark for the library adding it to `https://github.com/gabyx/ApproxMVBB/blob/master/benchmarks/CMakeLists.txt`
