### ISSUE TITLE
ApproxMVBB library version could not be determined!,GIT-NOTFOUND

### ISSUE THREAD

**Issue by niklaskarel** [gabyx/ApproxMVBB#40]
Hello,
I have read the ApproxMVBB library version could not be determined!, HEAD-HASH-NOTFOUND. 
Gabyx says get the repository with clone and not from .zip. I have done that and I still get this error (used Git Desktop).
Is there any solution to this ?
![image](https://user-images.githubusercontent.com/34400322/86819164-8f913e80-c087-11ea-8de4-639e27c27f50.png)

**Comment by gabyx** [comment]
Hi, yeah, I depend on tags for the version unfortunately, so make sure you clone the hole history not only depth=1 does it work then, if it doesnt, you can try adding another tag with „git tag  v1.2.2“ or so (check the version). I try to make this less cumbersome by adding a version file in the future.

Von meinem iPhone gesendet

**Comment by gabyx** [comment]
it seems you dont have git installed in your system! 

Von meinem iPhone gesendet

**Comment by gabyx** [comment]
I think you can already use the zipped version and build it as far as I see.
It should work ;-)! Can you test that?

**Comment by niklaskarel** [comment]
I have git but I used Github Desktop to clone this application. Sorry I am really a starter with both. I will try the .zip file.

**Comment by niklaskarel** [comment]
It configured. Thank you for your input
