### ISSUE TITLE
Just a correction to google test brach name

### ISSUE THREAD

**Issue by jediofgever** [gabyx/ApproxMVBB#47]
Hi, 
Not really an issue, but want to mention it. Github changed default branch naming from `master` -> `main`. 

The google test branch also needs to be renamed to `main`,
https://github.com/gabyx/ApproxMVBB/blob/58892b8f2ffc87257d0fd13d324a30339eced28e/tests/CMakeLists.txt#L5
otherwise, it fails to find the repository. 
Best.

**Comment by gabyx** [comment]
Thanks.

Fixed.
