### ISSUE TITLE
PCL point cloud as input

### ISSUE THREAD

**Issue by brunoeducsantos** [gabyx/ApproxMVBB#49]
Hi @gabyx  ,
Thanks for the excellent work. 

This post is not an issue, more like a question. I wonder if there is a way to provide the `approxMVBB` method with a `pcl point cloud` instead of a `Eigen Matrix` ?

Thanks,
Bruno

**Comment by brunoeducsantos** [comment]
One can use `getMatrixXfMap()` method. 
Thanks

**Comment by Rrycbarm** [comment]
@brunoeducsantos Could you please share a snippet of code? I'm trying to import a pcl pointcloud but I get a "YOU_MIXED_DIFFERENT_NUMERIC_TYPES__YOU_NEED_TO_USE_THE_CAST_METHOD_OF_MATRIXBASE_TO_CAST_NUMERIC_TYPES_EXPLICITLY" assertion failed and I'm not able to solve it.
